-- Optional sample data (SCAFFOLD). Empty for now.
-- TODO: a few tasks/goals/knowledge/events plus a couple of hand-authored
-- bubbles, useful for developing the board before the Brain is wired up.
